<?php

namespace Database\Seeders;

use App\Models\Bank;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BankSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Bank::insert([
            [
                "name" => "BANK BRI",
                "code" => "002",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK EKSPOR INDONESIA",
                "code" => "003",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK MANDIRI",
                "code" => "008",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK BNI",
                "code" => "009",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK DANAMON",
                "code" => "011",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "PERMATA BANK",
                "code" => "013",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK BCA",
                "code" => "014",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK BII",
                "code" => "016",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK PANIN",
                "code" => "019",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK ARTA NIAGA KENCANA",
                "code" => "020",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK NIAGA",
                "code" => "022",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK BUANA IND",
                "code" => "023",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK LIPPO",
                "code" => "026",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK NISP",
                "code" => "028",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "AMERICAN EXPRESS BANK LTD",
                "code" => "030",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "CITIBANK N.A.",
                "code" => "031",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "JP. MORGAN CHASE BANK, N.A.",
                "code" => "032",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK OF AMERICA, N.A",
                "code" => "033",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "ING INDONESIA BANK",
                "code" => "034",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK MULTICOR TBK.",
                "code" => "036",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK ARTHA GRAHA",
                "code" => "037",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK CREDIT AGRICOLE INDOSUEZ",
                "code" => "039",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "THE BANGKOK BANK COMP. LTD",
                "code" => "040",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "THE HONGKONG & SHANGHAI B.C.",
                "code" => "041",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "THE BANK OF TOKYO MITSUBISHI UFJ LTD",
                "code" => "042",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK SUMITOMO MITSUI INDONESIA",
                "code" => "045",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK DBS INDONESIA",
                "code" => "046",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK RESONA PERDANIA",
                "code" => "047",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK MIZUHO INDONESIA",
                "code" => "048",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "STANDARD CHARTERED BANK",
                "code" => "050",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK ABN AMRO",
                "code" => "052",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK KEPPEL TATLEE BUANA",
                "code" => "053",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK CAPITAL INDONESIA, TBK.",
                "code" => "054",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK BNP PARIBAS INDONESIA",
                "code" => "057",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK UOB INDONESIA",
                "code" => "058",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "KOREA EXCHANGE BANK DANAMON",
                "code" => "059",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "RABOBANK INTERNASIONAL INDONESIA",
                "code" => "060",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "ANZ PANIN BANK",
                "code" => "061",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "DEUTSCHE BANK AG.",
                "code" => "067",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK WOORI INDONESIA",
                "code" => "068",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK OF CHINA LIMITED",
                "code" => "069",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK BUMI ARTA",
                "code" => "076",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK EKONOMI",
                "code" => "087",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK ANTARDAERAH",
                "code" => "088",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK HAGA",
                "code" => "089",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK IFI",
                "code" => "093",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK CENTURY, TBK.",
                "code" => "095",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK MAYAPADA",
                "code" => "097",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK JABAR",
                "code" => "110",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK DKI",
                "code" => "111",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BPD DIY",
                "code" => "112",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK JATENG",
                "code" => "113",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK JATIM",
                "code" => "114",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BPD JAMBI",
                "code" => "115",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BPD ACEH",
                "code" => "116",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK SUMUT",
                "code" => "117",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK NAGARI",
                "code" => "118",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK RIAU",
                "code" => "119",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK SUMSEL",
                "code" => "120",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK LAMPUNG",
                "code" => "121",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BPD KALSEL",
                "code" => "122",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BPD KALIMANTAN BARAT",
                "code" => "123",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BPD KALTIM",
                "code" => "124",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BPD KALTENG",
                "code" => "125",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BPD SULSEL",
                "code" => "126",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK SULUT",
                "code" => "127",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BPD NTB",
                "code" => "128",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BPD BALI",
                "code" => "129",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK NTT",
                "code" => "130",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK MALUKU",
                "code" => "131",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BPD PAPUA",
                "code" => "132",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK BENGKULU",
                "code" => "133",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BPD SULAWESI TENGAH",
                "code" => "134",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK SULTRA",
                "code" => "135",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK NUSANTARA PARAHYANGAN",
                "code" => "145",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK SWADESI",
                "code" => "146",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK MUAMALAT",
                "code" => "147",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK MESTIKA",
                "code" => "151",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK METRO EXPRESS",
                "code" => "152",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK SHINTA INDONESIA",
                "code" => "153",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK MASPION",
                "code" => "157",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK HAGAKITA",
                "code" => "159",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK GANESHA",
                "code" => "161",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK WINDU KENTJANA",
                "code" => "162",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "HALIM INDONESIA BANK",
                "code" => "164",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK HARMONI INTERNATIONAL",
                "code" => "166",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK KESAWAN",
                "code" => "167",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK TABUNGAN NEGARA (PERSERO)",
                "code" => "200",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK HIMPUNAN SAUDARA 1906, TBK .",
                "code" => "212",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK TABUNGAN PENSIUNAN NASIONAL",
                "code" => "213",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK SWAGUNA",
                "code" => "405",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK JASA ARTA",
                "code" => "422",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK MEGA",
                "code" => "426",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK JASA JAKARTA",
                "code" => "427",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK BUKOPIN",
                "code" => "441",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK SYARIAH MANDIRI",
                "code" => "451",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK BISNIS INTERNASIONAL",
                "code" => "459",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK SRI PARTHA",
                "code" => "466",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK JASA JAKARTA",
                "code" => "472",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK BINTANG MANUNGGAL",
                "code" => "484",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK BUMIPUTERA",
                "code" => "485",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK YUDHA BHAKTI",
                "code" => "490",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK MITRANIAGA",
                "code" => "491",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK AGRO NIAGA",
                "code" => "494",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK INDOMONEX",
                "code" => "498",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK ROYAL INDONESIA",
                "code" => "501",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK ALFINDO",
                "code" => "503",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK SYARIAH MEGA",
                "code" => "506",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK INA PERDANA",
                "code" => "513",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK HARFA",
                "code" => "517",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "PRIMA MASTER BANK",
                "code" => "520",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK PERSYARIKATAN INDONESIA",
                "code" => "521",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK AKITA",
                "code" => "525",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "LIMAN INTERNATIONAL BANK",
                "code" => "526",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "ANGLOMAS INTERNASIONAL BANK",
                "code" => "531",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK DIPO INTERNATIONAL",
                "code" => "523",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK KESEJAHTERAAN EKONOMI",
                "code" => "535",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK UIB",
                "code" => "536",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK ARTOS IND",
                "code" => "542",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK PURBA DANARTA",
                "code" => "547",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK MULTI ARTA SENTOSA",
                "code" => "548",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK MAYORA",
                "code" => "553",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK INDEX SELINDO",
                "code" => "555",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK VICTORIA INTERNATIONAL",
                "code" => "566",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK EKSEKUTIF",
                "code" => "558",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "CENTRATAMA NASIONAL BANK",
                "code" => "559",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK FAMA INTERNASIONAL",
                "code" => "562",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK SINAR HARAPAN BALI",
                "code" => "564",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK HARDA",
                "code" => "567",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK FINCONESIA",
                "code" => "945",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK MERINCORP",
                "code" => "946",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK MAYBANK INDOCORP",
                "code" => "947",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK OCBC – INDONESIA",
                "code" => "948",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK CHINA TRUST INDONESIA",
                "code" => "949",
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                "name" => "BANK COMMONWEALTH",
                "code" => "950",
                'crated_at'  => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
