<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Employee;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $employees = [
            [
                'user_id' => 2,
                'ck_setting_id' => 1,
                'employee_id' => 'EMP002',
                'nik' => '987654321',
                'first_name' => 'Jane',
                'last_name' => 'Smith',
                'position_id' => 2,
                'address' => '456 Another Street',
                'email' => 'jane.smith@example.com',
                'phone' => '0987654321',
                'birth_place' => 'City B',
                'birth_date' => '1992-02-02',
                'education' => 'D4',
                'religion' => 'Islam',
                'gender' => 'Female',
                'blood_type' => 'A',
                'work_status' => 'Permanent', 
                'join_date' => '2021-02-01',
                'resign_date' => null,
                'salary' => '1500000',
                'employee_photo' => 'jane_smith.jpg',
                'employee_status' => 'Active',
            ],
            [
                'user_id' => 3,
                'ck_setting_id' => 2,
                'employee_id' => 'EMP003',
                'nik' => '112233445',
                'first_name' => 'Alice',
                'last_name' => 'Johnson',
                'position_id' => 3,
                'address' => '789 Third Street',
                'email' => 'alice.johnson@example.com',
                'phone' => '1122334455',
                'birth_place' => 'City C',
                'birth_date' => '1993-03-03',
                'education' => 'S1',
                'religion' => 'Hinduism',
                'gender' => 'Female',
                'blood_type' => 'B',
                'work_status' => 'Permanent', 
                'join_date' => '2022-03-01',
                'resign_date' => null,
                'salary' => '1500000',
                'employee_photo' => 'alice_johnson.jpg',
                'employee_status' => 'Active',
            ],
            [
                'user_id' => 4,
                'ck_setting_id' => 3,
                'employee_id' => 'EMP004',
                'nik' => '556677889',
                'first_name' => 'Bob',
                'last_name' => 'Brown',
                'position_id' => 4,
                'address' => '101 Fourth Street',
                'email' => 'bob.brown@example.com',
                'phone' => '5566778899',
                'birth_place' => 'City D',
                'birth_date' => '1994-04-04',
                'education' => 'S1',
                'religion' => 'Buddhism',
                'gender' => 'Male',
                'blood_type' => 'AB',
                'work_status' => 'Permanent', 
                'join_date' => '2023-04-01',
                'resign_date' => null,
                'salary' => '1500000',
                'employee_photo' => 'bob_brown.jpg',
                'employee_status' => 'Active',
            ],
            [
                'user_id' => 5,
                'ck_setting_id' => 1,
                'employee_id' => 'EMP005',
                'nik' => '667788990',
                'first_name' => 'Charlie',
                'last_name' => 'Davis',
                'position_id' => 5,
                'address' => '202 Fifth Street',
                'email' => 'charlie.davis@example.com',
                'phone' => '6677889900',
                'birth_place' => 'City E',
                'birth_date' => '1995-05-05',
                'education' => 'D3',
                'religion' => 'Christianity',
                'gender' => 'Male',
                'blood_type' => 'O',
                'work_status' => 'Permanent',
                'join_date' => '2024-05-01',
                'resign_date' => null,
                'salary' => '1500000',
                'employee_photo' => 'charlie_davis.jpg',
                'employee_status' => 'Active',
            ],
            [
                'user_id' => 7,
                'ck_setting_id' => 2,
                'employee_id' => 'EMP007',
                'nik' => '778899001',
                'first_name' => 'Diana',
                'last_name' => 'Evans',
                'position_id' => 7,
                'address' => '303 Sixth Street',
                'email' => 'diana.evans@example.com',
                'phone' => '7788990011',
                'birth_place' => 'City F',
                'birth_date' => '1996-06-06',
                'education' => 'SMA',
                'religion' => 'Islam',
                'gender' => 'Female',
                'blood_type' => 'A',
                'work_status' => 'Internship',
                'join_date' => '2025-06-01',
                'resign_date' => null,
                'salary' => '1500000',
                'employee_photo' => 'diana_evans.jpg',
                'employee_status' => 'Active',
            ],
            [
                'user_id' => 8,
                'ck_setting_id' => 3,
                'employee_id' => 'EMP008',
                'nik' => '889900112',
                'first_name' => 'Eve',
                'last_name' => 'Foster',
                'position_id' => 8,
                'address' => '404 Seventh Street',
                'email' => 'eve.foster@example.com',
                'phone' => '8899001122',
                'birth_place' => 'City G',
                'birth_date' => '1997-07-07',
                'education' => 'SMA',
                'religion' => 'Hinduism',
                'gender' => 'Female',
                'blood_type' => 'B',
                'work_status' => 'Part-time',
                'join_date' => '2026-07-01',
                'resign_date' => null,
                'salary' => '1500000',
                'employee_photo' => 'eve_foster.jpg',
                'employee_status' => 'Active',
            ],
            [
                'user_id' => 9,
                'ck_setting_id' => 1,
                'employee_id' => 'EMP009',
                'nik' => '990011223',
                'first_name' => 'Frank',
                'last_name' => 'Green',
                'position_id' => 9,
                'address' => '505 Eighth Street',
                'email' => 'frank.green@example.com',
                'phone' => '9900112233',
                'birth_place' => 'City H',
                'birth_date' => '1998-08-08',
                'education' => 'S2',
                'religion' => 'Buddhism',
                'gender' => 'Male',
                'blood_type' => 'AB',
                'work_status' => 'Outsource',
                'join_date' => '2027-08-01',
                'resign_date' => null,
                'salary' => '1500000',
                'employee_photo' => 'frank_green.jpg',
                'employee_status' => 'Active',
            ],
            [
                'user_id' => 10,
                'ck_setting_id' => 2,
                'employee_id' => 'EMP010',
                'nik' => '001122334',
                'first_name' => 'Grace',
                'last_name' => 'Harris',
                'position_id' => 10,
                'address' => '606 Ninth Street',
                'email' => 'grace.harris@example.com',
                'phone' => '0011223344',
                'birth_place' => 'City I',
                'birth_date' => '1999-09-09',
                'education' => 'S1',
                'religion' => 'Christianity',
                'gender' => 'Female',
                'blood_type' => 'O',
                'work_status' => 'Internship',
                'join_date' => '2028-09-01',
                'resign_date' => null,
                'salary' => '1500000',
                'employee_photo' => 'grace_harris.jpg',
                'employee_status' => 'Active',
            ],
        ];

        foreach ($employees as $employee) {
            Employee::create($employee);
        }
    }
}
