<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Employee;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $employees = [
            [
                'user_id' => 2,
                'company_id' => 'COMP001',
                // 'ck_setting_id' => 1,
                'employee_id' => 'EMP001',
                'nik' => '1234567890123401',
                'first_name' => 'Rick',
                'last_name' => 'Roll',
                'position_id' => 1,
                // 'department_id' => 2,
                'address' => '456 Another Street',
                'email' => 'rick.roll@example.com',
                'phone' => '+62987654322',
                'birth_place' => 'City B',
                'birth_date' => '1992-02-02',
                'education' => 'D4',
                'religion' => 'Islam',
                'gender' => 'Female',
                'marital_status' => 'Single',
                'blood_type' => 'A',
                'contract_type' => 'Permanent', 
                'join_date' => '2021-02-01',
                'exit_date' => null,
                'salary' => '1500000',
                'employee_status' => 'Active',
            ],
            [
                'user_id' => 3,
                'company_id' => 'COMP001',
                // 'ck_setting_id' => 1,
                'employee_id' => 'EMP002',
                'nik' => '1234567890123402',
                'first_name' => 'Jane',
                'last_name' => 'Smith',
                'position_id' => 2,
                // 'department_id' => 2,
                'address' => '456 Another Street',
                'email' => 'jane.smith@example.com',
                'phone' => '+62987654321',
                'birth_place' => 'City B',
                'birth_date' => '1992-02-02',
                'education' => 'D4',
                'religion' => 'Islam',
                'gender' => 'Female',
                'marital_status' => 'Single',
                'blood_type' => 'A',
                'contract_type' => 'Permanent', 
                'join_date' => '2021-02-01',
                'exit_date' => null,
                'salary' => '1500000',
                'employee_status' => 'Active',
            ],
            [
                'user_id' => 4,
                'company_id' => 'COMP001',
                // 'ck_setting_id' => 2,
                'employee_id' => 'EMP003',
                'nik' => '1234567890123403',
                'first_name' => 'Alice',
                'last_name' => 'Johnson',
                'position_id' => 3,
                // 'department_id' => 1,
                'address' => '789 Third Street',
                'email' => 'alice.johnson@example.com',
                'phone' => '+62812233445',
                'birth_place' => 'City C',
                'birth_date' => '1993-03-03',
                'education' => 'S1',
                'religion' => 'Hindu',
                'gender' => 'Female',
                'marital_status' => 'Married',
                'blood_type' => 'B',
                'contract_type' => 'Permanent', 
                'join_date' => '2022-03-01',
                'exit_date' => null,
                'salary' => '1500000',
                'employee_status' => 'Active',
            ],
            [
                'user_id' => 5,
                'company_id' => 'COMP001',
                // 'ck_setting_id' => 1,
                'employee_id' => 'EMP004',
                'nik' => '1234567890123404',
                'first_name' => 'Bob',
                'last_name' => 'Brown',
                'position_id' => 4,
                'address' => '101 Fourth Street',
                'email' => 'bob.brown@example.com',
                'phone' => '+628566778899',
                'birth_place' => 'City D',
                'birth_date' => '1994-04-04',
                // 'department_id' => 1,
                'education' => 'S1',
                'religion' => 'Buddhism',
                'gender' => 'Male',
                'marital_status' => 'Widowed',
                'blood_type' => 'AB',
                'contract_type' => 'Permanent', 
                'join_date' => '2023-04-01',
                'exit_date' => null,
                'salary' => '1500000',
                'employee_status' => 'Active',
            ],
            [
                'user_id' => 6,
                'company_id' => 'COMP001',
                // 'ck_setting_id' => 2,
                'employee_id' => 'EMP005',
                'nik' => '1234567890123405',
                'first_name' => 'Charlie',
                'last_name' => 'Davis',
                'position_id' => 5,
                'address' => '202 Fifth Street',
                'email' => 'charlie.davis@example.com',
                'phone' => '+628677889900',
                'birth_place' => 'City E',
                'birth_date' => '1995-05-05',
                // 'department_id' => 1,
                'education' => 'D3',
                'religion' => 'Christian',
                'gender' => 'Male',
                'marital_status' => 'Single',
                'blood_type' => 'O',
                'contract_type' => 'Permanent',
                'join_date' => '2024-05-01',
                'exit_date' => null,
                'salary' => '1500000',
                'employee_status' => 'Active',
            ],
            [
                'user_id' => 8,
                'company_id' => 'COMP002',
                // 'ck_setting_id' => 3,
                'employee_id' => 'EMP006',
                'nik' => '1234567890123406',
                'first_name' => 'Diana',
                'last_name' => 'Evans',
                'position_id' => 6,
                // 'department_id' => 2,
                'address' => '303 Sixth Street',
                'email' => 'diana.evans@example.com',
                'phone' => '+62878899001',
                'birth_place' => 'City F',
                'birth_date' => '1996-06-06',
                'education' => 'SMA',
                'religion' => 'Islam',
                'gender' => 'Female',
                'marital_status' => 'Single',
                'blood_type' => 'A',
                'contract_type' => 'Internship',
                'contract_end' => '2026-10-10',
                'join_date' => '2025-06-01',
                'exit_date' => null,
                'salary' => '1500000',
                'employee_status' => 'Active',
            ],
            [
                'user_id' => 9,
                'company_id' => 'COMP002',
                // 'ck_setting_id' => 3,
                'employee_id' => 'EMP007',
                'nik' => '1234567890123408',
                'first_name' => 'Eve',
                'last_name' => 'Foster',
                'position_id' => 8,
                // 'department_id' => 2,
                'address' => '404 Seventh Street',
                'email' => 'eve.foster@example.com',
                'phone' => '+62889900112',
                'birth_place' => 'City G',
                'birth_date' => '1997-07-07',
                'education' => 'SMA',
                'religion' => 'Hindu',
                'gender' => 'Female',
                'marital_status' => 'Single',
                'blood_type' => 'B',
                'contract_type' => 'Permanent',
                'join_date' => '2026-07-01',
                'exit_date' => null, 
                'salary' => '1500000',
                'employee_status' => 'Active',
            ],
            [
                'user_id' => 10,
                'company_id' => 'COMP002',
                // 'ck_setting_id' => 4,
                'employee_id' => 'EMP008',
                'nik' => '1234567890123409',
                'first_name' => 'Frank',
                'last_name' => 'Green',
                'position_id' => 9,
                // 'department_id' => 1,
                'address' => '505 Eighth Street',
                'email' => 'frank.green@example.com',
                'phone' => '+62890011223',
                'birth_place' => 'City H',
                'birth_date' => '1998-08-08',
                'education' => 'S2',
                'religion' => 'Buddhism',
                'gender' => 'Male',
                'marital_status' => 'Married',
                'blood_type' => 'AB',
                'contract_type' => 'Permanent',
                'join_date' => '2027-08-01',
                'exit_date' => null,
                'salary' => '1500000',
                'employee_status' => 'Active',
            ],
            [
                'user_id' => 11,
                'company_id' => 'COMP002',
                // 'ck_setting_id' => 4,
                'employee_id' => 'EMP009',
                'nik' => '1234567890123410',
                'first_name' => 'Grace',
                'last_name' => 'Harris',
                'position_id' => 10,
                // 'department_id' => 2,
                'address' => '606 Ninth Street',
                'email' => 'grace.harris@example.com',
                'phone' => '+628112233445',
                'birth_place' => 'City I',
                'birth_date' => '1999-09-09',
                'education' => 'S1',
                'religion' => 'Christian',
                'gender' => 'Female',
                'marital_status' => 'Married',
                'blood_type' => 'O',
                'contract_type' => 'Internship',
                'contract_end' => '2026-10-10',
                'join_date' => '2028-09-01',
                'exit_date' => null,
                'salary' => '1500000',
                'employee_status' => 'Active',
            ],
        ];

        foreach ($employees as $employee) {
            Employee::create($employee);
        }
    }
}
