name: Deploy Endpoint to Server via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout (for reading secrets only)
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22 
        script: |
          cd /home/$USER/hris_backend
          git pull origin main
          docker-compose exec app composer install --no-interaction --prefer-dist --optimize-autoloader
          docker-compose exec app php artisan migrate --force
          docker-compose exec app php artisan config:cache
